---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.4
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ${PERSISTENCE_DATA_PATH}:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 10 # Sets the default number of objects to be returned in a query.
      QUERY_MAXIMUM_RESULTS: 200000
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ASYNC_INDEXING: 'true' # If set, Weaviate creates vector indexes asynchronously to the object creation process. This can be useful for importing large amounts of data. (default: false)
      AUTOSCHEMA_ENABLED: 'false'
      DISABLE_TELEMETRY: 'true'
      # ENABLE_API_BASED_MODULES: 'false'
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_MODULES: backup-filesystem
      BACKUP_FILESYSTEM_PATH: /var/lib/weaviate/backups
